### ISSUE TITLE
请问batch size的问题，以及如何才能支持GPU半精度模型？[问题请教]

### ISSUE THREAD

**Issue by yimingchen027** [ncdhz/YoloV5-LibTorch#10]
请忽略开始的问题，发现自己犯了个错，YOLO export的时候用错了一些设置。
我希望检测一个视频，不知道怎样才能最大利用GPU。Batch size是可以大一点吗？
如果Yolo导出一个batch size 大于1的模型，不知道怎么在这里使用。
没有看到关于batch size的设定，是否在test.cpp里面预读几个image再塞到模型里面？
另外，如何才能支持GPU半精度模型？
谢谢指教！

**Comment by ncdhz** [comment]
@yimingchen027 std::vector<torch::Tensor> prediction(std::vector <cv::Mat> imgs);这个方法可以满足batch size大于一的情况，当然 std::vector<torch::Tensor> prediction(torch::Tensor data);这个也可以，半精度的代码我刚才更新了，设置一个参数就好了可以，你可以看看类的构造函数

**Comment by yimingchen027** [comment]
回复好迅速，收到，谢谢大神指点！
