### ISSUE TITLE
关于非极大值抑制函数的一个问题

### ISSUE THREAD

**Issue by 924726976** [ncdhz/YoloV5-LibTorch#12]
请问
std::vector<torch::Tensor> YoloV5::non_max_suppression(torch::Tensor prediction, float confThres, float iouThres)
函数里面，torch::Tensor c = x.slice(1, 5, 6) * maxWh;执行的作用是什么？

**Comment by 924726976** [comment]
思考了下，应该目的是
不同类别的box位置信息加上一个很大但是又不同的数
这样非极大值抑制的时候不同类别的框就不会掺和到一块了

**Comment by ncdhz** [comment]
@924726976  对类别信息是0到（n-1） 然后乘以 maxWh（一个很大的数）就变成了 （0, maxWh, 2*maxWh, ..., (n - 1) * maxWh） 就可以让不同类别的框在一起。
