### ISSUE TITLE
无法正确读取pt文件

### ISSUE THREAD

**Issue by lzmfor** [ncdhz/YoloV5-LibTorch#2]
- 麻烦，请教下
- py那边训练好的pt，c++程序读取后，运行，卡在 

`torch::Tensor pred = model.forward({ data }).toTuple()->elements()[0].toTensor();`

- 请问可能是什么问题
- 已经用export.py对pt文件进行了转换
```

std::vector<torch::Tensor> YoloV5::prediction(torch::Tensor data)
{
	if (!data.is_cuda() && this->isCuda)
	{
		data = data.cuda();
	}
	if (data.is_cuda() && !this->isCuda)
	{
		data = data.cpu();
	}
	torch::Tensor pred = model.forward({ data }).toTuple()->elements()[0].toTensor();
	return non_max_suppression(pred, confThres, iouThres);
}
```

**Comment by lzmfor** [comment]
- [https://github.com/yasenh/libtorch-yolov5](https://github.com/yasenh/libtorch-yolov5)

> ... ...
> Mandatory Update: developer needs to modify following code from the original export.py in yolov5
> ```
> model.model[-1].export = False
> ```
> ... ...

**Comment by ncdhz** [comment]
@lzmfor  解决了吧？没有看 github 尴尬

**Comment by lzmfor** [comment]
是的，可以了，谢谢
