### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by acu754** [ncdhz/YoloV5-LibTorch#3]
大佬，这里报错咋回事
![6FL)HWO(9CANZO78E{UX4WB](https://user-images.githubusercontent.com/68725193/137619563-83956fc6-8338-491b-8433-6d2e1007800a.png)

**Comment by ncdhz** [comment]
@acu754 更换 libtorch 版本尝试没有的？可能会存在 pytorch 转换的模型和 libtorch 版本不一致的情况。

**Comment by acu754** [comment]
> @acu754 更换 libtorch 版本尝试没有的？可能会存在 pytorch 转换的模型和 libtorch 版本不一致的情况。

我用了1.9.1和1.8.1都不行

**Comment by ncdhz** [comment]
@acu754 需要的话加我 QQ：1137436221 我得看看你的操作啥的
