### ISSUE TITLE
Crop and save bounding box libtorch c++

### ISSUE THREAD

**Issue by problemSolvingProgramming** [ncdhz/YoloV5-LibTorch#6]
Hi, I want to add crop and save bounding box libtorch c ++ to the following code, but unfortunately I do not know exactly, I can crop one person, but if there are several objects in an image, I can not crop or save them with different boundix. Thank you very much for helping us or writing the code.?

https://github.com/Nebula4869/YOLOv5-LibTorch

**Comment by ncdhz** [comment]
You can try the std::vector<torch::Tensor> prediction function

**Comment by problemSolvingProgramming** [comment]
@ncdhz  thank you . I'm going to crop any object that was human or person into its bounding box and give it to a dl whose function input is matte to return a name. (For the face recognition part of who this object is) and what it has in hand I want to use.

I do not know how to write this in C ++.

https://github.com/Nebula4869/YOLOv5-LibTorch
