### ISSUE TITLE
cmake编译不通过

### ISSUE THREAD

**Issue by wanshenfake** [ncdhz/YoloV5-LibTorch#8]
cuda 11.3 nvcc8.3 libtorch 1.10 opencv4.5.5
![1](https://user-images.githubusercontent.com/38283960/150525869-1c4f7eb2-2cb5-4267-91e5-1fa8650c8ca7.JPG)

**Comment by ncdhz** [comment]
再试一下，我又改了一点东西。

**Comment by wanshenfake** [comment]
还是不行,libtorch和opencv用的哪个版本能说一下吗

**Comment by ncdhz** [comment]
我今天试了一下最新版本的opencv和cuda 10.2 最新版本的 libtorch 可以
libtorch: https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.10.2%2Bcu102.zip 
opencv: OpenCV–4.5.5

**Comment by xugaoxiang** [comment]
@ncdhz ，用了同款组合，也出现了题主的错误。

**Comment by xugaoxiang** [comment]
将 YoloV5.h 中的中文注释删除，编译通过，。

**Comment by ncdhz** [comment]
@xugaoxiang 强呀，这是编码问题吗
